name: Secure Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-sign-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # needed for cosign keyless
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/wendiblac/secure-supply-chain-demo:dev-v1


      - name: Cosign Sign + Attest
        uses: sigstore/cosign-installer@v3
      - run: |
          cosign sign --keyless ghcr.io/wendiblac/secure-supply-chain-demo:dev-v1
          cosign attest --keyless --predicate sbom.json --type spdx ghcr.io/wendiblac/secure-supply-chain-demo:dev-v1
