name: Sign and Verify Container Image

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write   # required for keyless signing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo:ci
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Image (keyless)
        run: cosign sign $IMAGE

      - name: Verify Image
        run: cosign verify $IMAGE
