# .github/workflows/trivy-scan.yml
name: Container Security Scan

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t demo:ci .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo:ci
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Generate SBOM (CycloneDX)
        run: trivy image --format cyclonedx --output sbom.json demo:ci

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
